export const surpriseMePrompts = [
  "A futuristic city",
  "A dragon flying over mountains",
  "A robot playing chess",
  "A cozy cabin in the forest",
  "A surreal landscape with melting clocks",
  "A neon-lit street at night",
  "A galaxy with candy planets",
  "An astronaut on Mars",
  "A cat in space",
  "A pirate ship in the clouds",
  "A crystal palace",
  "A steampunk airship",
  "A wizard in a forest",
  "A futuristic car",
  "A beach sunset",
  "A snowy mountain peak",
  "A bustling market",
  "A peaceful waterfall",
  "A castle in the sky",
  "A train speeding through a desert",
  "A meadow full of flowers",
  "A whale swimming in the sky",
  "A floating island",
  "A jungle at dawn",
  "A lighthouse on a cliff",
  "A robot garden",
  "A dreamlike staircase to the stars",
  "A quiet library",
  "A dragon made of fire",
  "A magical treehouse",
  "A colorful coral reef",
  "A vintage airplane flying through clouds",
  "A glowing forest at night",
  "A spaceship landing on a new planet",
  "A mystical lake",
  "A street filled with umbrellas",
  "A giant mushroom forest",
  "A sunken treasure chest",
  "A mountain village",
  "A carnival at night",
  "A desert with giant cacti",
  "A bird flying over the ocean",
  "A moonlit desert",
  "A futuristic bridge",
  "A train station in the rain",
  "A giant robot in a city",
  "A fantasy castle on a hill",
  "A bridge to another world",
  "A mysterious forest path",
  "A cozy coffee shop",
  "A spaceship traveling through a wormhole",
  "A sunflower field at sunset",
  "A glass house in the forest",
  "A mountain range with floating islands",
  "A fairy tale castle",
  "A cat sitting on a floating cloud",
  "A mystical forest",
  "A waterfall inside a cave",
  "A rainbow over the ocean",
  "A field of lavender",
  "A futuristic city skyline",
  "A glowing crystal cave",
  "A boat sailing on a peaceful lake",
  "A glowing moon over a desert",
  "A giant tree in the middle of a village",
  "A bridge across a canyon",
  "A floating city in the clouds",
  "A flower garden in the rain",
  "A street filled with colorful lanterns",
  "A planet made entirely of ice",
  "A fairy flying through a forest",
  "A magical forest clearing",
  "A dragon sleeping in a cave",
  "A city under the sea",
  "A robot factory",
  "A snow-covered village",
  "A magical bookstore",
  "A futuristic robot dog",
  "A river flowing through a canyon",
  "A tree with glowing fruit",
  "A space station orbiting Earth",
  "A fantasy forest with glowing plants",
  "A glowing underwater world",
  "A whale swimming beneath the northern lights",
  "A futuristic skyscraper",
  "A waterfall flowing into the ocean",
  "A market in a small village",
  "A sailboat in a stormy sea",
  "A train crossing a mountain pass",
  "A quiet alley in a city at night",
  "A starry sky over a desert",
  "A treehouse in a magical forest",
  "A spaceship traveling through the stars",
  "A cabin in the woods",
  "A jungle waterfall",
  "A floating mountain range",
  "A robot working in a garden",
  "A desert with an oasis",
  "A futuristic hoverboard",
  "A flower garden under the stars",
  "A futuristic plane flying over mountains",
];
